name: Continuous Integration

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # We install necessary drivers so we can run our tests
      - name: Install Chromium
        run: sudo apt-get install chromium-browser

      # We need to checkout current branch
      - uses: actions/checkout@v2

      # As it's a NodeJS project, we need to setup NodeJS into our environment
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '20.x'

      # We did not check node_modules directory to GitHub so we need to install dependencies
      - name: Install dependencies
        run: npm install

      # We execute our test execution command
      - name: Running E2E tests
        run: npx wdio wdio.conf.ts

      # Generates the allure report
      - name: Generate Allure report
        run: npx allure generate --clean

      # Publishes the allure report to GitHub Pages
      - name: Publish Allure report
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: allure-report
        env:
          GITHUB_TOKEN: ${{ secrets.GHCR_PAT }}
